[2023-07-21T16:03:58.095+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2023-07-21T16:03:52.249720+00:00 [queued]>
[2023-07-21T16:03:58.101+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2023-07-21T16:03:52.249720+00:00 [queued]>
[2023-07-21T16:03:58.101+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-07-21T16:03:58.101+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-07-21T16:03:58.101+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-07-21T16:03:58.110+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2023-07-21 16:03:52.249720+00:00
[2023-07-21T16:03:58.114+0000] {standard_task_runner.py:55} INFO - Started process 15675 to run task
[2023-07-21T16:03:58.118+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2023-07-21T16:03:52.249720+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp4bnsugn7']
[2023-07-21T16:03:58.119+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask store_user
[2023-07-21T16:03:58.170+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.store_user manual__2023-07-21T16:03:52.249720+00:00 [running]> on host 9d876987b8ed
[2023-07-21T16:03:58.220+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-07-21T16:03:52.249720+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-21T16:03:52.249720+00:00
[2023-07-21T16:03:58.221+0000] {postgres.py:129} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2023-07-21T16:03:58.230+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-07-21T16:03:58.235+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 30, in _store_user
    filename='/tmp/processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 137, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY users, line 1: "Aubree,Matthews,United States,orangemouse429,clown,aubree.matthews@example.com"

[2023-07-21T16:03:58.244+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=store_user, execution_date=20230721T160352, start_date=20230721T160358, end_date=20230721T160358
[2023-07-21T16:03:58.251+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task store_user (extra data after last expected column
CONTEXT:  COPY users, line 1: "Aubree,Matthews,United States,orangemouse429,clown,aubree.matthews@example.com"
; 15675)
[2023-07-21T16:03:58.290+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-07-21T16:03:58.307+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
