[2023-07-21T15:55:50.670+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2023-07-21T15:55:43.674561+00:00 [queued]>
[2023-07-21T15:55:50.677+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2023-07-21T15:55:43.674561+00:00 [queued]>
[2023-07-21T15:55:50.677+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-07-21T15:55:50.677+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-07-21T15:55:50.677+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-07-21T15:55:50.685+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2023-07-21 15:55:43.674561+00:00
[2023-07-21T15:55:50.690+0000] {standard_task_runner.py:55} INFO - Started process 15261 to run task
[2023-07-21T15:55:50.694+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2023-07-21T15:55:43.674561+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpipm1ehbj']
[2023-07-21T15:55:50.695+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask store_user
[2023-07-21T15:55:50.748+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.store_user manual__2023-07-21T15:55:43.674561+00:00 [running]> on host 9d876987b8ed
[2023-07-21T15:55:50.798+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2023-07-21T15:55:43.674561+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-21T15:55:43.674561+00:00
[2023-07-21T15:55:50.799+0000] {postgres.py:129} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2023-07-21T15:55:50.807+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-07-21T15:55:50.814+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 30, in _store_user
    filename='/tmp/processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 137, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY users, line 1: "Isabel,Lorenzo,Spain,sadelephant655,bomber,isabel.lorenzo@example.com"

[2023-07-21T15:55:50.822+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=store_user, execution_date=20230721T155543, start_date=20230721T155550, end_date=20230721T155550
[2023-07-21T15:55:50.829+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task store_user (extra data after last expected column
CONTEXT:  COPY users, line 1: "Isabel,Lorenzo,Spain,sadelephant655,bomber,isabel.lorenzo@example.com"
; 15261)
[2023-07-21T15:55:50.865+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-07-21T15:55:50.883+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
